# Generated by Django 4.0.3 on 2022-03-27 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('V', 'Vrouwen'), ('M', 'Mannen'), ('X', 'Mix')], max_length=1)),
                ('naam', models.CharField(max_length=255)),
                ('speeltijd', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Speelronde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('V', 'Vrouwen'), ('M', 'Mannen'), ('X', 'Mix')], max_length=1)),
                ('naam', models.CharField(max_length=255)),
                ('spelers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wedstrijd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntenTeam1', models.PositiveSmallIntegerField()),
                ('puntenTeam2', models.PositiveSmallIntegerField()),
                ('poule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeachPortalApi.poule')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='BeachPortalApi.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='BeachPortalApi.team')),
            ],
            options={
                'verbose_name_plural': 'Wedstrijden',
            },
        ),
        migrations.AddField(
            model_name='poule',
            name='speelronde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BeachPortalApi.speelronde'),
        ),
        migrations.AddField(
            model_name='poule',
            name='teams',
            field=models.ManyToManyField(to='BeachPortalApi.team'),
        ),
    ]
