# Generated by Django 4.0.3 on 2022-05-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeachPortalApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoomlaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('block', models.IntegerField()),
                ('sendEmail', models.IntegerField(blank=True, db_column='sendEmail', null=True)),
                ('registerdate', models.DateTimeField(db_column='registerDate')),
                ('lastvisitdate', models.DateTimeField(db_column='lastvisitDate')),
                ('activation', models.CharField(max_length=100)),
                ('params', models.TextField()),
                ('lastresettime', models.DateTimeField(db_column='lastResetTime')),
                ('resetcount', models.IntegerField(db_column='resetCount')),
                ('otpkey', models.CharField(db_column='otpKey', max_length=1000)),
                ('otep', models.CharField(max_length=1000)),
                ('requirereset', models.IntegerField(db_column='requireReset')),
            ],
            options={
                'db_table': 'J3_users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
