# Generated by Django 4.0.3 on 2022-05-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeachPortalApi', '0002_joomlauser_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speellocatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.TextField()),
            ],
        ),
    ]
