# Generated by Django 4.0.3 on 2022-06-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeachPortalApi', '0002_alter_speler_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('receiver', models.EmailField(max_length=254)),
                ('title', models.TextField()),
                ('message', models.TextField()),
                ('signature', models.TextField(unique=True)),
                ('dateSent', models.DateTimeField(null=True)),
            ],
        ),
    ]
