# Generated by Django 4.0.3 on 2022-05-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeachPortalApi', '0003_speellocatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='poule',
            name='speellocatie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='BeachPortalApi.speellocatie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poule',
            name='speelronde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poules', to='BeachPortalApi.speelronde'),
        ),
    ]
