# Generated by Django 4.0.3 on 2022-05-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeachPortalApi', '0004_poule_speellocatie_alter_poule_speelronde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poule',
            name='categorie',
            field=models.CharField(choices=[('V', 'Dames'), ('M', 'Heren'), ('X', 'Mix')], max_length=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='categorie',
            field=models.CharField(choices=[('V', 'Dames'), ('M', 'Heren'), ('X', 'Mix')], max_length=1),
        ),
    ]
