# Generated by Django 4.0.3 on 2022-05-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeachPortalApi', '0005_alter_poule_categorie_alter_team_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poule',
            name='categorie',
            field=models.CharField(choices=[('D', 'Dames'), ('H', 'Heren'), ('X', 'Mix')], max_length=1),
        ),
        migrations.AlterField(
            model_name='poule',
            name='speellocatie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='speellocaties', to='BeachPortalApi.speellocatie'),
        ),
        migrations.AlterField(
            model_name='poule',
            name='teams',
            field=models.ManyToManyField(blank=True, to='BeachPortalApi.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='categorie',
            field=models.CharField(choices=[('D', 'Dames'), ('H', 'Heren'), ('X', 'Mix')], max_length=1),
        ),
    ]
