# Generated by Django 4.0.3 on 2022-05-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeachPortalApi', '0006_alter_poule_categorie_alter_poule_speellocatie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poule',
            name='naam',
        ),
        migrations.AddField(
            model_name='poule',
            name='nummer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wedstrijd',
            name='poule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedstrijden', to='BeachPortalApi.poule'),
        ),
    ]
